{% set version = "0.8.4" %}
{% set sha256 = "3ff413b0f4f85861ac993917767c1f131cd18e279ca26784e407ce905bf71236" %}

package:
  name: back_to_sequences
  version: {{ version }}

source:
  url: https://github.com/pierrepeterlongo/back_to_sequences/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('back_to_sequences', max_pin='x') }}

requirements:
  build:
    - {{ compiler('rust') }}

test:
  commands:
    - back_to_sequences --help

about:
  home: https://github.com/pierrepeterlongo/back_to_sequences
  doc_url: https://b2s-doc.readthedocs.io/
  license: AGPL-3.0-only
  license_file: LICENSE
  summary: Find the origin of kmers - extract sequences containing queried kmers

extra:
  recipe-maintainers:
    - pierrepeterlongo
